name: update-songs

on:
  schedule:
    # every 2 days, at 23:23 UTC
    - cron: '23 23 */2 * *'
  workflow_dispatch:

jobs:
  updateSongList:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}

      - name: Replace song list
        uses: ./.github/actions/fetchList/
        with:
          API_ENDPOINT: ${{secrets.API_ENDPOINT}}

      - name: Get personal access token username
        id: get_pat_username
        run: |
          echo "ci_pat_user=$(curl -s https://${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}:@api.github.com/user | jq -r .name)" >> $GITHUB_OUTPUT
          echo "ci_pat_email=$(curl -s https://${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}:@api.github.com/user | jq -r .email)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Commit changes
        run: |
          git config --local user.name "${{ steps.get_pat_username.outputs.ci_pat_user }}"
          git config --local user.email "${{ steps.get_pat_username.outputs.ci_pat_email }}"
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            exit 0
          fi
          git commit -m "chore: Update song list"
          git push
